In [2]:
import torch  

1.矩阵：

In [32]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
A.T #转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

2.对称矩阵：转置矩阵与原矩阵相同

In [7]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [8]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

3.矩阵推广--（简单理解：标量是0维，向量是1维，矩阵是2维，下面的X,Y就是对矩阵的再推广,X是3维，Y是4维）
**注意:**

1.   向量的长度通常称为向量的维度（dimension）。
2.   维度（dimension）这个词在不同上下文时往往会有不同的含义，这经常会使人感到困惑。 为了清楚起见，我们在此明确一下： 向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。 然而，张量的维度用来表示张量具有的轴数。 在这个意义上，张量的某个轴的维数就是这个轴的长度。


In [15]:
X = torch.arange(24).reshape(2,3,4)
Y = torch.arange(36).reshape(3,3,4)
print(X)
print(Y)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])


4.降维：

In [25]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum(),x.shape

(tensor([0., 1., 2., 3.]), tensor(6.), torch.Size([4]))

从这里就可以看到x.sum()输出的是一个0维的，原来的x是一个1维的

指定沿着哪一个轴降维：

In [12]:
A_sum_axis0 = A.sum(axis = 0)#相当于按列求和
A_sum_axis0, A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

这里我指定按照0轴降维，原来是2维，我只沿一个轴降维，自然的，就变为了1维

In [16]:
B = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B.mean()#计算按所有轴降维计算平均值，说白了就是将A中的所有元素相加求平均值,注意这个方法，只能是针对元素是float类型，int类型不支持

tensor(9.5000)

In [15]:
B.numel()#计算元素个数

20

5.非降维方法

意思就是说，如上文中，A.sum()输出的必然是降维的。如何求某些和且不降维

In [19]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [18]:
sum_B = B.sum(axis=1, keepdims=True)#指定按照1轴求和
sum_B#还是2维

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

cumsum也是不降维，只不过他的功能是沿着某一个(e.g. 1轴)轴，B00=B00,B01=B00+B01,B02=B00+B01+B02...

In [21]:
B.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

6.向量的点积

In [22]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

点积的几何意义是：
点乘的结果表示在方向上的投影与的乘积，反映了两个向量在方向上的相似度，结果越大越相似。基于结果可以判断这两个向量是否是同一方向，是否正交垂直

**a**点积**b**>0说明方向基本相同，夹角在0-90之间，=0说明垂直，<0说明方向基本相反，夹角在90-180之间

7.矩阵向量积

In [27]:
B.shape, x.shape, torch.mv(B, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

8.矩阵的乘法

In [35]:
C = torch.ones(3, 4)
torch.mm(B, C)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

9.范数

In [36]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)